verbose = true

exclude = [
  "adlic.rjfun.com",
  "https://github.com/admob-plus/admob-plus/blob/",
  "https://npmjs.org/package/admob-plus-cordova-native",
  "https://admob-plus.github.io/docs/cordova/ads/native",
]
